#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 11 21:43:51 2021

@author: wajih
"""

import torch
import random
import os
import glob
from copy import deepcopy
from flask import Flask, render_template, request
import json
import datetime
import sys,os
from flask import Flask, render_template, request, redirect, url_for

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/', methods=['POST'])
def upload_file():
    uploaded_file = request.files['html-file']
    if uploaded_file.filename != '':
        uploaded_file.save(uploaded_file.filename)
    return redirect(url_for('index'))

if __name__ == '__main__':     
    app.run(host='0.0.0.0', port=8000, debug=True)    
